{% set version = "5.7.1" %}

package:
  name: oct2py
  version: {{ version }}

source:
  fn: oct2py-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/o/oct2py/oct2py-{{ version }}.tar.gz
  sha256: b99deddf8670eaebafb0de663c9d01d74bf8664fb5c32546e77971f3cfddbba7

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6
    - numpy
    - scipy
    - ipython
    - octave_kernel >=0.34.0
    - hatchling
  run:
    - python >=3.6
    - numpy
    - scipy
    - ipython
    - octave_kernel >=0.34.0

about:
  home: http://github.com/blink1073/oct2py
  license: MIT
  license_file: LICENSE.txt
  summary: Python to GNU Octave bridge --> run m-files from python.

extra:
  recipe-maintainers:
    - blink1073
    - ocefpaf
