{% set version = "6.0.0" %}

package:
  name: oct2py
  version: {{ version }}

source:
  fn: oct2py-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/o/oct2py/oct2py-{{ version }}.tar.gz
  sha256: 915073fcd9f97b28cbc30527f3b7651dacc8e15a94299968e764cbc0165851e1

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - numpy
    - scipy
    - ipython
    - octave_kernel >=0.34.0
    - hatchling
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - ipython
    - octave_kernel >=0.34.0

about:
  home: http://github.com/blink1073/oct2py
  license: MIT
  license_file: LICENSE.txt
  summary: Python to GNU Octave bridge --> run m-files from python.

extra:
  recipe-maintainers:
    - blink1073
    - ocefpaf
