{% set version = "5.4.3" %}

package:
  name: oct2py
  version: {{ version }}

source:
  fn: oct2py-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/o/oct2py/oct2py-{{ version }}.tar.gz
  sha256: 92311451b35750559776bfdf1344cd55ed7a66add8a16d03623bd55bf0cbd0e8

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6
    - numpy
    - scipy
    - ipython
    - octave_kernel >=0.34.0
    - setuptools
  run:
    - python >=3.6
    - numpy
    - scipy
    - ipython
    - octave_kernel >=0.34.0

about:
  home: http://github.com/blink1073/oct2py
  license: MIT
  license_file: LICENSE.txt
  summary: Python to GNU Octave bridge --> run m-files from python.

extra:
  recipe-maintainers:
    - blink1073
    - ocefpaf
