{% set version = "5.8.0" %}

package:
  name: oct2py
  version: {{ version }}

source:
  fn: oct2py-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/o/oct2py/oct2py-{{ version }}.tar.gz
  sha256: 2b5e86a9de1d62adcc90ae6795f9e33302f7eef649ce3cef671d1be8b4b5804b

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - numpy
    - scipy
    - ipython
    - octave_kernel >=0.34.0
    - hatchling
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - ipython
    - octave_kernel >=0.34.0

about:
  home: http://github.com/blink1073/oct2py
  license: MIT
  license_file: LICENSE.txt
  summary: Python to GNU Octave bridge --> run m-files from python.

extra:
  recipe-maintainers:
    - blink1073
    - ocefpaf
